### ISSUE TITLE
[website_crm_extended] contactform cannot be submitted any longer in Version o8r73

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#102]
# Bug Summary
/page/website-contactus Form on Website does not allow to submit the Form since update with the new Adress fields. This is not the Case if you are logged in as Administrator and do the same test. 

## How to Reproduce
1. Open Browser
2. Go to Page http://127.0.0.1:8069/page/website.contactus
3. fill out and submit

### Current Result
403 Error Message if not logged in
Email SENT by System does not copy the "spenderservice" this was done by the system before update

### Expected Result
thanks for your info .... bla ... page should be shown 

## Bug Source
- Instance: ```pfot``` --> local TEst DB
- Record/Model: mail.template
- Reported by: testuserplzvn testuserplznm
- Reported at: 10.jul.2017

# Additional Information (optional)
Logged in as Admin this error does not happen 
Logout and do it as ebsite User error 403 is shown 

2017-07-10 09:47:48,693 47509 WARNING pfot_update openerp.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 3, model: email.template
2017-07-10 09:47:48,696 47509 WARNING pfot_update openerp.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 3, model: email.template
2017-07-10 09:47:48,697 47509 WARNING pfot_update openerp.addons.website.models.ir_http: 403 Forbidden:

Traceback (most recent call last):
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r73/odoo/addons/website/models/ir_http.py", line 199, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r73/odoo/openerp/addons/base/ir/ir_http.py", line 145, in _handle_exception
    return request._handle_exception(exception)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r73/odoo/openerp/http.py", line 668, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r73/odoo/openerp/addons/base/ir/ir_http.py", line 171, in _dispatch
    result = request.dispatch()
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r73/odoo/openerp/http.py", line 686, in dispatch
    r = self._call_function(**self.params)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r73/odoo/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r73/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r73/odoo/openerp/http.py", line 309, in checked_call
    return self.endpoint(*a, **kw)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r73/odoo/openerp/http.py", line 805, in __call__
    return self.method(*args, **kw)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r73/odoo/openerp/http.py", line 405, in response_wrap
    response = f(*args, **kw)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r73/addons-loaded/website_snippet_contact_form/controllers/main.py", line 16, in contactus
    res = super(snippetContactus, self).contactus(**kwargs)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r73/odoo/openerp/http.py", line 405, in response_wrap
    response = f(*args, **kw)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r73/odoo/addons/website_crm/controllers/main.py", line 96, in contactus
    lead_id = self.create_lead(request, dict(values, user_id=False), kwargs)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r73/addons-loaded/website_crm_extended/controllers/main.py", line 43, in create_lead
    rendered_template_body = email_template.render_template_batch(template=template.body_html,
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r73/odoo/openerp/fields.py", line 834, in __get__
    self.determine_value(record)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r73/odoo/openerp/fields.py", line 927, in determine_value
    record._prefetch_field(self)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r73/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r73/odoo/openerp/models.py", line 3245, in _prefetch_field
    result = self.read(list(fnames), load='_classic_write')
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r73/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r73/odoo/openerp/models.py", line 3162, in read
    self.check_access_rights('read')
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r73/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r73/odoo/openerp/api.py", line 487, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r73/odoo/openerp/models.py", line 3505, in check_access_rights
    return self.pool.get('ir.model.access').check(cr, uid, self._name, operation, raise_exception)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r73/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in check
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r73/odoo/openerp/tools/cache.py", line 122, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r73/odoo/openerp/addons/base/ir/ir_model.py", line 769, in check
    raise openerp.exceptions.AccessError(msg % msg_params)
AccessError: ('AccessError', u'Entschuldigen Sie, Sie sind nicht berechtigt auf dieses Dokument zuzugreifen. Nur Benutzer mit dem folgenden Zugriffslevel sind zur Zeit berechtigt:\n- Human Resources/Employee\n\t- Administration/Settings\n\n(Dokumentenmodell: email.template)')

2017-07-10 09:47:48,776 47509 INFO pfot_update werkzeug: 127.0.0.1 - - [10/Jul/2017 09:47:48] "POST /crm/contactus HTTP/1.1" 403 -
Neues Verhalten -- kein Informed via Email
![nachrichten_-_odoo_neues_verhalten_loggedin](https://user-images.githubusercontent.com/5407843/28013286-cfb7617e-6568-11e7-865b-fac3c0d51677.jpg)
Altes Verhalten
![nachrichten_-_odoo](https://user-images.githubusercontent.com/5407843/28013287-cfbb836c-6568-11e7-8203-3105690d6a65.jpg)
Website-Verkäufe Setup
![nachrichten_verkaufsteams_-_odoo](https://user-images.githubusercontent.com/5407843/28013577-ca594656-6569-11e7-9720-b0cbc889db2b.jpg)

User Settings for Email 
![nachrichten_spenderservice_mailsetup_user](https://user-images.githubusercontent.com/5407843/28013600-dc983944-6569-11e7-8f07-536086bcf7a2.jpg)

**Comment by winston6071** [comment]
ADDITIONAL INFORMATION for UPDATE PROCESS with option -u all 

2017-07-10 09:22:51,510 47509 INFO pfot_update openerp.addons.base.ir.ir_translation: module payment_ogonedadi: loading translation file (de) for language de_DE
2017-07-10 09:22:51,510 47509 INFO pfot_update openerp.tools.translate: loading /Users/joe/entwicklung/gitrepo/online/online_o8r73/addons-loaded/payment_ogonedadi/i18n/de.po
2017-07-10 09:22:52,976 47509 INFO pfot_update openerp.modules.module: module fsonline: creating or updating database tables
2017-07-10 09:22:52,983 47509 INFO pfot_update openerp.modules.loading: loading fsonline/data/user_studio.xml
2017-07-10 09:22:53,842 47509 WARNING pfot_update openerp.addons.base.ir.ir_translation: module fsonline: no translation for language de
2017-07-10 09:22:53,844 47509 INFO pfot_update openerp.modules.loading: 186 modules loaded in 341.17s, 7 queries
2017-07-10 09:22:56,026 47509 INFO pfot_update openerp.addons.base.ir.ir_model: Deleting 609@ir.ui.menu (fso_base.menu_fsonline_apf_partner_fields_menu)
2017-07-10 09:22:56,060 47509 INFO pfot_update openerp.addons.base.ir.ir_model: Deleting 2088@ir.ui.view (website_pfoh.pfot_contactus_form)
2017-07-10 09:22:56,077 47509 INFO pfot_update openerp.addons.base.ir.ir_model: Deleting 85@res.groups (base.sosync)
2017-07-10 09:22:56,255 47509 INFO pfot_update openerp.addons.base.ir.ir_model: Deleting 109@res.users (base.user_sosync)
2017-07-10 09:23:57,796 47509 INFO pfot_update openerp.addons.base.ir.ir_model: Deleting 139@mail.alias (base.user_sosync_mail_alias)
2017-07-10 09:23:57,797 47509 INFO pfot_update openerp.addons.base.ir.ir_model: Deleting 868@res.partner (base.user_sosync_res_partner)
2017-07-10 09:24:01,202 47509 INFO None openerp.http: Generating nondb routing
2017-07-10 09:24:01,212 47509 INFO None werkzeug: 127.0.0.1 - - [10/Jul/2017 09:24:01] "GET / HTTP/1.1" 200 -
2017-07-10 09:24:01,281 47509 INFO None werkzeug: 127.0.0.1 - - [10/Jul/2017 09:24:01] "GET /web HTTP/1.1" 303 -
2017-07-10 09:24:01,304 47509 INFO None werkzeug: 127.0.0.1 - - [10/Jul/2017 09:24:01] "GET /web/database/selector HTTP/1.1" 200 -
2017-07-10 09:24:01,314 47509 INFO ? werkzeug: 127.0.0.1 - - [10/Jul/2017 09:24:01] "GET /web/static/lib/fontawesome/css/font-awesome.css HTTP/1.1" 200 -
2017-07-10 09:24:01,314 47509 INFO ? werkzeug: 127.0.0.1 - - [10/Jul/2017 09:24:01] "GET /web/static/src/css/base.css HTTP/1.1" 200 -
2017-07-10 09:24:01,315 47509 INFO ? werkzeug: 127.0.0.1 - - [10/Jul/2017 09:24:01] "GET /web/static/lib/bootstrap/css/bootstrap.css HTTP/1.1" 200 -
2017-07-10 09:24:01,320 47509 INFO ? werkzeug: 127.0.0.1 - - [10/Jul/2017 09:24:01] "GET /web/static/src/img/logo2.png HTTP/1.1" 200 -
2017-07-10 09:24:14,910 47509 INFO pfot_update openerp.addons.base.ir.ir_model: Deleting 868@res.partner (base.partner_sosync)
2017-07-10 09:24:15,405 47509 INFO pfot_update openerp.modules.loading: Modules loaded.
2017-07-10 09:24:15,409 47509 INFO pfot_update openerp.models: Computing parent left and right for table ir_ui_menu...
2017-07-10 09:24:15,658 47509 INFO pfot_update openerp.models: Computing parent left and right for table website_menu...
2017-07-10 09:24:19,677 47509 INFO None werkzeug: 127.0.0.1 - - [10/Jul/2017 09:24:19] "GET /web?db=pfot_update HTTP/1.1" 302 -
2017-07-10 09:24:19,687 47509 INFO pfot_update openerp.addons.base.ir.ir_http: Generating routing map

**Comment by michaelkarrer81** [comment]
Kann den Fehler nicht reproduzieren bitte um Rücksprache

**Comment by michaelkarrer81** [comment]
Closed reopen if not ;)
