### ISSUE TITLE
o8r77 [website_sale_donate] OPC Checkout auf der GRID SEITE Fehler beim Return bei IBAN und BIC

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#111]
# Bug Summary
Nach Klick auf jetzt Spenden beim OPC GRID View One Page Checkout error 500

## How to Reproduce
Datenbank Bird --> Lokal 
anlegen Category --> grid 
root category --> JA 
Onepage Checkout --> JA
Enable "add to cart" im rechts oben menü auf der Website des Grid Layouts  
6 Produkte erstellt die auf 
/shop/category/grid-4 angezeigt werden 
Checkout eines Produktes 
Eingabe aller Daten und klick auf weiter 
Fehler beim Return siehe log 

### Current Result
http://127.0.0.1:8069/payment/frst/feedback
500: Internal Server Error

### Expected Result
/shopt/confirmation_static should be displayd

## Bug Source
- Instance: ```bird_update lokal``` 

# Additional Information (optional)
```
2017-08-03 09:27:26,646 40873 INFO bird_update werkzeug: 127.0.0.1 - - [03/Aug/2017 09:27:26] "POST /longpolling/poll HTTP/1.1" 200 -
2017-08-03 09:28:16,656 40873 INFO bird_update werkzeug: 127.0.0.1 - - [03/Aug/2017 09:28:16] "POST /longpolling/poll HTTP/1.1" 200 -
2017-08-03 09:29:06,670 40873 INFO bird_update werkzeug: 127.0.0.1 - - [03/Aug/2017 09:29:06] "POST /longpolling/poll HTTP/1.1" 200 -
2017-08-03 09:29:48,666 40873 WARNING bird_update openerp.addons.website_sale_donate.controllers.main: shop(): START <Request 'http://127.0.0.1:8069/shop/category/grid-4?category=4' [POST]>
2017-08-03 09:29:48,666 40873 WARNING bird_update openerp.addons.website_sale_donate.controllers.main: shop(): END, return super(website_sale_donate, self).shop(...)
2017-08-03 09:29:48,784 40873 WARNING bird_update openerp.addons.website_sale_donate.controllers.main: checkout(): START <Request 'http://127.0.0.1:8069/shop/category/grid-4?category=4' [POST]>
2017-08-03 09:29:48,822 40873 WARNING bird_update openerp.addons.website_sale_donate.controllers.main: checkout(): One-Page-Checkout is enabled and checkout_page is not just a redirection
2017-08-03 09:29:48,822 40873 WARNING bird_update openerp.addons.website_sale_donate.controllers.main: checkout(): OPC STEP 1: UPDATE DELIVERY
2017-08-03 09:29:48,822 40873 WARNING bird_update openerp.addons.website_sale_donate.controllers.main: checkout(): OPC STEP 2: RUN CONFIRM ORDER
2017-08-03 09:29:49,382 40873 WARNING bird_update openerp.addons.website_sale_donate.controllers.main: checkout(): OPC STEP 3: RUN THE ORIGINAL CHECKOUT CONTROLLER AGAIN
2017-08-03 09:29:49,439 40873 WARNING bird_update openerp.addons.website_sale_donate.controllers.main: checkout(): OPC STEP 4: RENDER THE PAYMENT BUTTONS (opc_payment())
2017-08-03 09:29:49,439 40873 WARNING bird_update openerp.addons.website_sale_donate.controllers.main: opc_payment(): START
2017-08-03 09:29:49,439 40873 WARNING bird_update openerp.addons.website_sale_donate.controllers.main: opc_payment(): 'acquirer' (ID: 3) found in post
2017-08-03 09:29:49,439 40873 WARNING bird_update openerp.addons.website_sale_donate.controllers.main: opc_payment(): add 'acquirer' to session
2017-08-03 09:29:49,439 40873 WARNING bird_update openerp.addons.website_sale_donate.controllers.main: opc_payment(): CREATE THE PAYMENT TRANSACTION AND UPDATE THE SALE ORDER
2017-08-03 09:29:49,439 40873 WARNING bird_update openerp.addons.website_sale_donate.controllers.main: payment_transaction_logic(): START
2017-08-03 09:29:49,439 40873 INFO bird_update openerp.addons.website_sale_donate.controllers.main: payment_transaction_logic(): call original payment_transaction()
2017-08-03 09:29:49,440 40873 WARNING bird_update openerp.addons.website_sale_donate.controllers.main: opc_payment(): run super().payment(**post)
2017-08-03 09:29:49,516 40873 WARNING bird_update openerp.addons.payment_frst.models.frst: frst_form_generate_values(): tx_values: {'currency_id': 1, 'currency': res.currency(1,), 'amount': 0.0, 'reference': '/', 'partner': res.partner(7227,), 'return_url': '/shop/payment/validate'}
2017-08-03 09:29:49,526 40873 WARNING bird_update openerp.addons.payment_ogonedadi.models.ogonedadi: ogonedadi_form_generate_values(): ogonedadi_tx_values: {'ORDERID': '/', 'PARAMPLUS': 'return_url=/shop/payment/validate', 'CN': u'Testspender3333 Testspender3333', 'reference': '/', 'OWNERTELNO': False, 'CURRENCY': u'EUR', 'OWNERCTY': u'AT', 'currency_id': 1, 'currency': res.currency(1,), 'DECLINEURL': u'https://www.birdlife.at/payment/ogonedadi/test/decline', 'SHASIGN': '03153baf7dd9ec3c8de1ec177796215460c1ee1f', 'partner': res.partner(7227,), 'ACCEPTURL': u'https://www.birdlife.at/payment/ogonedadi/test/accept', 'OWNERADDRESS': u'teststrasse', 'EMAIL': u'Testspender3333.Testspender3333@Testspender3333.com', 'LANGUAGE': u'de_DE', 'PSPID': u'birdprod', 'OWNERTOWN': u'Graz', 'EXCEPTIONURL': u'https://www.birdlife.at/payment/ogonedadi/test/exception', 'OWNERZIP': u'8020', 'AMOUNT': '0', 'amount': 0.0, 'CANCELURL': u'https://www.birdlife.at/payment/ogonedadi/test/cancel', 'BRAND': u'MasterCard', 'PM': u'CreditCard'}
2017-08-03 09:29:49,532 40873 WARNING bird_update openerp.addons.payment_ogonedadi.models.ogonedadi: ogonedadi_form_generate_values(): ogonedadi_tx_values: {'ORDERID': '/', 'PARAMPLUS': 'return_url=/shop/payment/validate', 'CN': u'Testspender3333 Testspender3333', 'reference': '/', 'OWNERTELNO': False, 'CURRENCY': u'EUR', 'OWNERCTY': u'AT', 'currency_id': 1, 'currency': res.currency(1,), 'DECLINEURL': u'https://www.birdlife.at/payment/ogonedadi/test/decline', 'SHASIGN': 'c77c35422bda5b625c5ac57e6b3adf3ab216cd07', 'partner': res.partner(7227,), 'ACCEPTURL': u'https://www.birdlife.at/payment/ogonedadi/test/accept', 'OWNERADDRESS': u'teststrasse', 'EMAIL': u'Testspender3333.Testspender3333@Testspender3333.com', 'LANGUAGE': u'de_DE', 'PSPID': u'birdprod', 'OWNERTOWN': u'Graz', 'EXCEPTIONURL': u'https://www.birdlife.at/payment/ogonedadi/test/exception', 'OWNERZIP': u'8020', 'AMOUNT': '0', 'amount': 0.0, 'CANCELURL': u'https://www.birdlife.at/payment/ogonedadi/test/cancel', 'BRAND': u'PAYPAL', 'PM': u'PAYPAL'}
2017-08-03 09:29:49,537 40873 WARNING bird_update openerp.addons.payment_ogonedadi.models.ogonedadi: ogonedadi_form_generate_values(): ogonedadi_tx_values: {'ORDERID': '/', 'PARAMPLUS': 'return_url=/shop/payment/validate', 'CN': u'Testspender3333 Testspender3333', 'reference': '/', 'OWNERTELNO': False, 'CURRENCY': u'EUR', 'OWNERCTY': u'AT', 'currency_id': 1, 'currency': res.currency(1,), 'DECLINEURL': u'https://www.birdlife.at/payment/ogonedadi/test/decline', 'SHASIGN': 'c3a38fa1eb6a9ce125c9124faec2634308f030a7', 'partner': res.partner(7227,), 'ACCEPTURL': u'https://www.birdlife.at/payment/ogonedadi/test/accept', 'OWNERADDRESS': u'teststrasse', 'EMAIL': u'Testspender3333.Testspender3333@Testspender3333.com', 'LANGUAGE': u'de_DE', 'PSPID': u'birdprod', 'OWNERTOWN': u'Graz', 'EXCEPTIONURL': u'https://www.birdlife.at/payment/ogonedadi/test/exception', 'OWNERZIP': u'8020', 'AMOUNT': '0', 'amount': 0.0, 'CANCELURL': u'https://www.birdlife.at/payment/ogonedadi/test/cancel', 'BRAND': u'Sofort Uberweisung', 'PM': u'DirectEbanking'}
2017-08-03 09:29:49,542 40873 WARNING bird_update openerp.addons.payment_ogonedadi.models.ogonedadi: ogonedadi_form_generate_values(): ogonedadi_tx_values: {'ORDERID': '/', 'PARAMPLUS': 'return_url=/shop/payment/validate', 'CN': u'Testspender3333 Testspender3333', 'reference': '/', 'OWNERTELNO': False, 'CURRENCY': u'EUR', 'OWNERCTY': u'AT', 'currency_id': 1, 'currency': res.currency(1,), 'DECLINEURL': u'https://www.birdlife.at/payment/ogonedadi/test/decline', 'SHASIGN': 'b0fd488c6d10dd327a7becf77760f2794fc719ae', 'partner': res.partner(7227,), 'ACCEPTURL': u'https://www.birdlife.at/payment/ogonedadi/test/accept', 'OWNERADDRESS': u'teststrasse', 'EMAIL': u'Testspender3333.Testspender3333@Testspender3333.com', 'LANGUAGE': u'de_DE', 'PSPID': u'birdprod', 'OWNERTOWN': u'Graz', 'EXCEPTIONURL': u'https://www.birdlife.at/payment/ogonedadi/test/exception', 'OWNERZIP': u'8020', 'AMOUNT': '0', 'amount': 0.0, 'CANCELURL': u'https://www.birdlife.at/payment/ogonedadi/test/cancel', 'BRAND': u'VISA', 'PM': u'CreditCard'}
2017-08-03 09:29:49,545 40873 WARNING bird_update openerp.addons.website_sale_donate.controllers.main: opc_payment(): CHECK FOR ERRORS
2017-08-03 09:29:49,545 40873 WARNING bird_update openerp.addons.website_sale_donate.controllers.main: opc_payment(): ADD acquirer_id TO QCONTEXT
2017-08-03 09:29:49,545 40873 WARNING bird_update openerp.addons.website_sale_donate.controllers.main: opc_payment(): add "acquirer_id" to qcontext
2017-08-03 09:29:49,545 40873 WARNING bird_update openerp.addons.website_sale_donate.controllers.main: opc_payment(): CHECK IF THERE IS ALREADY A PAYMENT TRANSACTION LINKED TO THE SO
2017-08-03 09:29:49,545 40873 WARNING bird_update openerp.addons.website_sale_donate.controllers.main: opc_payment(): ADD EXTRA INFORMATION TO QCONTEXT FOR OPC TEMPLATES
2017-08-03 09:29:49,547 40873 WARNING bird_update openerp.addons.website_sale_donate.controllers.main: opc_payment(): CHANGE ORIGINAL ACQUIRER BUTTON FORMS
2017-08-03 09:29:49,549 40873 WARNING bird_update openerp.addons.website_sale_donate.controllers.main: opc_payment(): ACQUIRER SELECTION AND VALIDATION
2017-08-03 09:29:49,553 40873 WARNING bird_update openerp.addons.website_sale_donate.controllers.main: opc_payment(): ADD 'acquirer_auto_submit' TO QCONTEXT
2017-08-03 09:29:49,553 40873 WARNING bird_update openerp.addons.website_sale_donate.controllers.main: opc_payment(): MOVE ACQUIRERS WITH globally_hidden TO acquirers_hidden
2017-08-03 09:29:49,557 40873 WARNING bird_update openerp.addons.website_sale_donate.controllers.main: opc_payment(): END
2017-08-03 09:29:49,557 40873 WARNING bird_update openerp.addons.website_sale_donate.controllers.main: checkout(): OPC STEP 5: CHECK FOR ERRORS
2017-08-03 09:29:49,557 40873 WARNING bird_update openerp.addons.website_sale_donate.controllers.main: checkout(): SUCCESS! RETURNING CHECKOUTPAGE WITH 'acquirer_auto_submit' FOR PP REDIRECT!
2017-08-03 09:29:49,785 40873 INFO bird_update werkzeug: 127.0.0.1 - - [03/Aug/2017 09:29:49] "POST /shop/category/grid-4?category=4 HTTP/1.1" 200 -
2017-08-03 09:29:49,971 40873 INFO bird_update openerp.addons.payment_frst.controllers.main: Beginn Form Feedback for FRST PaymentProvider with post data {'amount': u'0.0',
 'currency': u'EUR',
 'frst_bic': u'BKAUATWW',
 'frst_iban': u'AT411100000237571500',
 'reference': u'/',
 'return_url': u'/shop/payment/validate'}
2017-08-03 09:29:49,976 40873 ERROR bird_update openerp.addons.payment_frst.models.frst: FRST Payment Transaction: received data for reference u'/'; no Transaction found
2017-08-03 09:29:49,977 40873 INFO bird_update openerp.addons.website_sale_donate.models.payment_transaction: Could not find a payment transaction before form_feedback()
2017-08-03 09:29:49,980 40873 ERROR bird_update openerp.addons.payment_frst.models.frst: FRST Payment Transaction: received data for reference u'/'; no Transaction found
2017-08-03 09:29:50,007 40873 INFO bird_update werkzeug: 127.0.0.1 - - [03/Aug/2017 09:29:50] "POST /website/translations HTTP/1.1" 200 -
2017-08-03 09:29:50,012 40873 ERROR bird_update openerp.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r77/odoo/addons/website/models/ir_http.py", line 199, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r77/odoo/openerp/addons/base/ir/ir_http.py", line 145, in _handle_exception
    return request._handle_exception(exception)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r77/odoo/openerp/http.py", line 675, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r77/odoo/openerp/addons/base/ir/ir_http.py", line 171, in _dispatch
    result = request.dispatch()
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r77/odoo/openerp/http.py", line 693, in dispatch
    r = self._call_function(**self.params)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r77/odoo/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r77/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r77/odoo/openerp/http.py", line 316, in checked_call
    return self.endpoint(*a, **kw)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r77/odoo/openerp/http.py", line 812, in __call__
    return self.method(*args, **kw)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r77/odoo/openerp/http.py", line 412, in response_wrap
    response = f(*args, **kw)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r77/addons-loaded/payment_frst/controllers/main.py", line 23, in frst_form_feedback
    request.registry['payment.transaction'].form_feedback(cr, uid, post, 'frst', context)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r77/addons-loaded/website_sale_donate/models/payment_transaction.py", line 37, in form_feedback
    res = super(PaymentTransaction, self).form_feedback(cr, uid, data, acquirer_name, context=context)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r77/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r77/odoo/addons/payment/models/payment_acquirer.py", line 475, in form_feedback
    tx = getattr(self, tx_find_method_name)(cr, uid, data, context=context)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r77/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/Users/joe/entwicklung/gitrepo/online/online_o8r77/addons-loaded/payment_frst/models/frst.py", line 102, in _frst_form_get_tx_from_data
    raise ValidationError(error_msg)
ValidationError: FRST Payment Transaction: received data for reference u'/'; no Transaction found

2017-08-03 09:29:50,048 40873 INFO bird_update werkzeug: 127.0.0.1 - - [03/Aug/2017 09:29:50] "POST /payment/frst/feedback HTTP/1.1" 500 -
2017-08-03 09:29:50,057 40873 INFO ? werkzeug: 127.0.0.1 - - [03/Aug/2017 09:29:50] "GET /website/static/src/css/website.css HTTP/1.1" 200 -
2017-08-03 09:29:56,683 40873 INFO bird_update werkzeug: 127.0.0.1 - - [03/Aug/2017 09:29:56] "POST /longpolling/poll HTTP/1.1" 200 -
2017-08-03 09:30:02,845 40873 INFO bird_update werkzeug: 127.0.0.1 - - [03/Aug/2017 09:30:02] "POST /calendar/notify HTTP/1.1" 200 -
```

**Comment by winston6071** [comment]
NOCH NICHT GETESTET MASTERCARD bzw. OGONE Provider da der Return noch nicht geht ... einrichten einer sauberen Testumgebung.... ist mit DADI bereits am laufen

**Comment by michaelkarrer81** [comment]
Dieses Verhalten ging wie besprochen auf einen Konfigurationsfehler zurück.
