### ISSUE TITLE
aahs Update auf o8r79 Failed

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#115]
# Bug Summary

## Bug Source

# Additional Information (optional)
```
2017-08-09 10:13:58,412 17974 INFO aahs_update openerp.addons.base.ir.ir_translation: module website_sale_donate: loading base translation file en for language en_US
2017-08-09 10:13:58,412 17974 INFO aahs_update openerp.tools.translate: loading /opt/online/online_o8r79/addons-loaded/website_sale_donate/i18n/en.po
2017-08-09 10:13:58,424 17974 INFO aahs_update openerp.addons.base.ir.ir_translation: module website_sale_donate: loading translation file (de) for language de_DE
2017-08-09 10:13:58,425 17974 INFO aahs_update openerp.tools.translate: loading /opt/online/online_o8r79/addons-loaded/website_sale_donate/i18n/de.po
2017-08-09 10:13:58,607 17974 INFO aahs_update openerp.addons.base.ir.ir_translation: module website_sale_donate: loading translation file (fr_CH) for language fr_CH
2017-08-09 10:13:58,607 17974 INFO aahs_update openerp.tools.translate: loading /opt/online/online_o8r79/addons-loaded/website_sale_donate/i18n/fr_CH.po
2017-08-09 10:13:58,753 17974 INFO aahs_update openerp.addons.base.ir.ir_translation: module website_sale_donate: loading translation file (it) for language it_IT
2017-08-09 10:13:58,753 17974 INFO aahs_update openerp.tools.translate: loading /opt/online/online_o8r79/addons-loaded/website_sale_donate/i18n/it.po
2017-08-09 10:14:00,416 17974 INFO aahs_update openerp.modules.module: module ahch_config: creating or updating database tables
2017-08-09 10:14:00,466 17974 INFO aahs_update openerp.modules.loading: loading ahch_config/views/templates.xml
2017-08-09 10:14:00,591 17974 ERROR aahs_update openerp.addons.base.ir.ir_ui_view: Element '<xpath expr="//h1[@class='payment_status']">' kann nicht in der übergeordneten Ansicht lokalisiert werden.

Fehler Kontext:
Ansicht `Confirmation Static AAHS`
[view_id: 1903, xml_id: ahch_config.confirmation_static_aahs, model: k. A., parent_id: 1844]
2017-08-09 10:14:00,593 17974 CRITICAL aahs_update openerp.service.server: Failed to initialize database `aahs_update`.
Traceback (most recent call last):
  File "/opt/online/online_o8r79/odoo/openerp/service/server.py", line 941, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/opt/online/online_o8r79/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/online/online_o8r79/odoo/openerp/modules/loading.py", line 350, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/opt/online/online_o8r79/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/online/online_o8r79/odoo/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/online/online_o8r79/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/online/online_o8r79/odoo/openerp/tools/convert.py", line 897, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/online/online_o8r79/odoo/openerp/tools/convert.py", line 983, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/online/online_o8r79/odoo/openerp/tools/convert.py", line 849, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/online/online_o8r79/odoo/openerp/tools/convert.py", line 823, in _tag_template
    return self._tag_record(cr, record, data_node)
  File "/opt/online/online_o8r79/odoo/openerp/tools/convert.py", line 759, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/online/online_o8r79/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/online/online_o8r79/odoo/openerp/addons/base/ir/ir_model.py", line 1023, in _update
    model_obj.write(cr, uid, [res_id], values, context=context)
  File "/opt/online/online_o8r79/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/online/online_o8r79/odoo/openerp/addons/base/ir/ir_ui_view.py", line 281, in write
    context)
  File "/opt/online/online_o8r79/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/online/online_o8r79/odoo/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/online/online_o8r79/odoo/openerp/models.py", line 3814, in write
    self._write(old_vals)
  File "/opt/online/online_o8r79/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/online/online_o8r79/odoo/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/opt/online/online_o8r79/odoo/openerp/models.py", line 3993, in _write
    recs._validate_fields(vals)
  File "/opt/online/online_o8r79/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/online/online_o8r79/odoo/openerp/models.py", line 1275, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Feld(er) 'arch' verletzen eine Einschr\xe4nkung: Invalid view definition

Fehlerdetails:
Element '<xpath expr="//h1[@class='payment_status']">' kann nicht in der \xfcbergeordneten Ansicht lokalisiert werden.

Fehler Kontext:
Ansicht `Confirmation Static AAHS`
[view_id: 1903, xml_id: ahch_config.confirmation_static_aahs, model: k. A., parent_id: 1844]" while parsing None:17, near
<data inherit_id="website_sale_donate.confirmation_static" name="Confirmation Static AAHS">
            <xpath expr="//h1[@class='payment_status']" position="after">
                <t t-call="website_sale_donate.small_cart">
                    <t t-set="show_download_links" t-value="True"/>
                    <t t-set="disable_changing_products" t-value="True"/>
                    <t t-set="website_sale_order" t-value="order"/>
                </t>
            </xpath>
        </data>
2017-08-09 10:14:00,596 17974 INFO aahs_update openerp.service.server: Initiating shutdown
2017-08-09 10:14:00,596 17974 INFO aahs_update openerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown.


---------- ERROR: UPDATE FAILED! ----------
```

**Comment by winston6071** [comment]
solved in commit c52f7ab6a7b34b289ddb7a251583c0c6b0c69186
