### ISSUE TITLE
Installation improvement -- move standard website fetures into one single menu item "demo" 

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#128]
# Bug Summary
everytime an update or a new installation is done standard website menu entries are shown at the menü
especially for customers using only ZMR or even others a big improvement and timesaving would be to have a little module which moves "deleted items from website" menü into a single menü item called "demo".
or at a naked installation it moves all menü items into this new created "menü" item. 

herer is a list of existing Items after new installation 
Home --> stays as it is 
Shop
Events 
Forum
News
Jobs 
Contact us
Documentation

# Manual action right now
create Menü Item "Demo" and its website "demo"
move all Items listed above inside this Item 

Install website_menu_by_user_status --> goto "settings" "configuration" "Configure website menus" "unset ulogged users" 

## Bug Source
- Instance: ```all``` 

# Additional Information (optional)

**Comment by winston6071** [comment]
to be rechecked in next installation 
at installtion of website_menu_by_user_status Module error message

DIESER FEHLER IST NICHT MEHR AUFGETRETEN BEI DEN ANDEREN INSTANZEN -- ES SCHEINT ALS WÄRE DAS AUFGRUND EINES KLICKS GEWESEN IM BACKEND MENÜ 

2017-10-17 07:40:03,672 1531 INFO npha werkzeug: 192.168.37.127 - - [17/Oct/2017 07:40:03] "POST /web/dataset/call_kw/share.wizard/has_share HTTP/1.0" 200 -
2017-10-17 07:40:03,751 1531 ERROR npha openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/online/online_o8r101/odoo/openerp/http.py", line 546, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/online/online_o8r101/odoo/openerp/http.py", line 583, in dispatch
    result = self._call_function(**self.params)
  File "/opt/online/online_o8r101/odoo/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/online/online_o8r101/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/online/online_o8r101/odoo/openerp/http.py", line 316, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/online/online_o8r101/odoo/openerp/http.py", line 812, in __call__
    return self.method(*args, **kw)
  File "/opt/online/online_o8r101/odoo/openerp/http.py", line 412, in response_wrap
    response = f(*args, **kw)
  File "/opt/online/online_o8r101/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/online/online_o8r101/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/online/online_o8r101/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/online/online_o8r101/odoo/openerp/addons/base/module/module.py", line 150, in fields_view_get
    res = super(module, self).fields_view_get(cr, uid, view_id=view_id, view_type=view_type, context=context, toolbar=toolbar, submenu=False)
  File "/opt/online/online_o8r101/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/online/online_o8r101/odoo/openerp/models.py", line 1528, in fields_view_get
    root_view = View.read_combined(cr, uid, view_id, fields=['id', 'name', 'field_parent', 'type', 'model', 'arch'], context=context)
  File "/opt/online/online_o8r101/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/online/online_o8r101/odoo/openerp/addons/base/ir/ir_ui_view.py", line 557, in read_combined
    cr, uid, arch_tree, root_id, base.model, context=context)
  File "/opt/online/online_o8r101/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/online/online_o8r101/odoo/openerp/addons/base/ir/ir_ui_view.py", line 500, in apply_view_inheritance
    sql_inherit = self.get_inheriting_views_arch(cr, uid, source_id, model, context=context)
  File "/opt/online/online_o8r101/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/online/online_o8r101/odoo/openerp/addons/base/ir/ir_ui_view.py", line 329, in get_inheriting_views_arch
    user = self.pool['res.users'].browse(cr, 1, uid, context=context)
  File "/opt/online/online_o8r101/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/online/online_o8r101/odoo/openerp/models.py", line 5304, in browse
    return self._browse(Environment(cr, uid, context or {}), ids)
  File "/opt/online/online_o8r101/odoo/openerp/api.py", line 763, in __new__
    for env in envs:
  File "/usr/lib/python2.7/_weakrefset.py", line 60, in __iter__
    for itemref in self.data:
RuntimeError: Set changed size during iteration
2017-10-17 07:40:03,788 1531 INFO npha werkzeug: 192.168.37.127 - - [17/Oct/2017 07:40:03] "POST /web/dataset/call_kw/ir.module.module/fields_view_get HTTP/1.0" 200 -
2017-10-17 07:40:03,811 1531 INFO npha werkzeug: 192.168.37.127 - - [17/Oct/2017 07:40:03] "POST /web/dataset/call_kw/ir.module.module/fields_view_get HTTP/1.0" 200 -
2017-10-17 07:40:03,989 1531 INFO npha werkzeug: 192.168.37.127 - - [17/Oct/2017 07:40:03] "POST /web/dataset/call_kw/ir.filters/get_filters HTTP/1.0" 200 -
