### ISSUE TITLE
BACKUP Script bricht bei zumindest bei einer Datenbank ab

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#133]
# Bug Summary
ImBackup Ordner von Pfot sind seit 01.Nov nur mehr 0 Byte Backups 
Manueller Start des Backups via db-tools.sh scheint nicht mehr zu funktionieren

## How to Reproduce
ausführen von 
```
/opt/online/online_tools/db-tools.py -b ****** -s ******** -x ***.datadialog.net backup -d *** -f /opt/onlinebackupdir/pfot/pfot-odoo_db-2017_11_27-08-36_weekly.zip
```

This bug can not be reproduced and occures after 3 to 4 mins when Backup is started

### Current Result
Backup not finished and stops working with memory error 

### Expected Result
Backup should be finished an file should be created with the database Backup 

## Bug Source
- Instance: ```pfot``` 
- Record/Model: 
- Reported by: 
- Reported at: 25.11.2017

# Additional Information (optional)
server: <ServerProxy for ***.datadialog.net/xmlrpc/db>
Traceback (most recent call last):
  File "/opt/online/online_tools/db-tools.py", line 106, in <module>
    args.func(args)
  File "/opt/online/online_tools/db-tools.py", line 41, in backup
    f.write(server.dump(args.superpwd, args.database).decode('base64'))
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1306, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1476, in parse_response
    p.feed(data)
  File "/usr/lib/python2.7/xmlrpclib.py", line 558, in feed
    self._parser.Parse(data, 0)
  File "/usr/lib/python2.7/xmlrpclib.py", line 824, in end
    return f(self, join(self._data, ""))
  File "/usr/lib/python2.7/xmlrpclib.py", line 873, in end_string
    self.append(_stringify(data))
  File "/usr/lib/python2.7/xmlrpclib.py", line 184, in _stringify
    return string.encode("ascii")
MemoryError

**Comment by winston6071** [comment]
because sometimes the backup just dont run, i tried to create a solution that not all backups getting startet at the same time. 

check if it becomes better after this change. But it does not explain the problem above, this was replied by manual start as well on command line. 

further Testing using ' for the password when using it manualy on command line
