### ISSUE TITLE
Screenshot gerneration for newsletter doesnt work

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#231]
2021-07-28 09:04:07,839 20310 INFO cona openerp.addons.fso_sosync.models.sosync_job_queue: Processed 2 Sync Jobs
2021-07-28 09:04:21,308 20525 ERROR cona openerp.addons.fso_base.tools.image: Could not generate screen-shot! TimeoutException()
2021-07-28 09:04:21,314 20525 ERROR cona openerp.addons.fso_website_email.models.email_template: Screenshot generation failed! AssertionError('Could not create screenshot_img!',)
2021-07-28 09:04:21,315 20525 INFO cona openerp.addons.fso_website_email.models.email_template: File /var/tmp/emailtemplate_36__20210728_090402_0918779nd_Iu.html for screenshot generation will be closed and deleted!
2021-07-28 09:04:21,326 20525 ERROR cona openerp.addons.connector.controllers.main: Traceback (most recent call last):
  File "/opt/online/cores/online_o8r436/addons-loaded/connector/controllers/main.py", line 96, in runjob
    self._try_perform_job(session_hdl, job)
  File "/opt/online/cores/online_o8r436/addons-loaded/connector/controllers/main.py", line 66, in _try_perform_job
    job.perform(session)
  File "/opt/online/cores/online_o8r436/addons-loaded/connector/queue/job.py", line 512, in perform
    self.result = self.func(session, *self.args, **self.kwargs)
  File "/opt/online/cores/online_o8r436/addons-loaded/fso_website_email_screenshot_async/job.py", line 37, in render_screenshot
    template.screenshot_update()
  File "/opt/online/cores/online_o8r436/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/online/cores/online_o8r436/addons-loaded/fso_website_email/models/email_template.py", line 368, in screenshot_update
    raise e
AssertionError: Could not create screenshot_img!

2021-07-28 09:04:21,344 20307 INFO cona openerp.modules.registry: At least one model cache has been cleared, signaling through the database.
2021-07-28 09:04:21,346 20307 INFO cona werkzeug: 192.168.37.113 - - [28/Jul/2021 09:04:21] "POST /web/dataset/call HTTP/1.1" 200 -
2021-07-28 09:04:21,374 20525 INFO cona openerp.modules.registry: At least one model cache has been cleared, signaling through the database.
2021-07-28 09:04:21,404 20307 INFO cona werkzeug: 192.168.37.113 - - [28/Jul/2021 09:04:21] "GET /website/image/ir.attachment/125_2404594/datas HTTP/1.1" 200 -
2021-07-28 09:04:21,415 20307 INFO cona openerp.modules.registry: Invalidating all model caches after database signaling.
2021-07-28 09:04:21,422 20525 INFO cona werkzeug: 127.0.0.1 - - [28/Jul/2021 09:04:21] "GET /connector/runjob?db=cona&job_uuid=fc289592-0e9c-4000-bcc4-4362f34d7dd2 HTTP/1.1" 500 -
2021-07-28 09:04:21,446 20525 ERROR cona werkzeug: Error on request:
Traceback (most recent call last):
  File "/opt/online/cores/python-2.7.16/lib/python2.7/site-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/opt/online/cores/python-2.7.16/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/opt/online/cores/online_o8r436/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/opt/online/cores/online_o8r436/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/online/cores/online_o8r436/odoo/openerp/http.py", line 1299, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/online/cores/online_o8r436/odoo/openerp/http.py", line 1273, in __call__
    return self.app(environ, start_wrapped)
  File "/opt/online/cores/python-2.7.16/lib/python2.7/site-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/opt/online/cores/online_o8r436/odoo/openerp/http.py", line 1273, in __call__
    return self.app(environ, start_wrapped)
  File "/opt/online/cores/python-2.7.16/lib/python2.7/site-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/opt/online/cores/online_o8r436/odoo/openerp/http.py", line 1453, in dispatch
    result = ir_http._dispatch()
  File "/opt/online/cores/online_o8r436/addons-own/auth_partner/models/ir_http.py", line 33, in _dispatch
    return super(ir_http, self)._dispatch()
  File "/opt/online/cores/online_o8r436/odoo/addons/website/models/ir_http.py", line 148, in _dispatch
    resp = super(ir_http, self)._dispatch()
  File "/opt/online/cores/online_o8r436/odoo/addons/crm/ir_http.py", line 13, in _dispatch
    response = super(ir_http, self)._dispatch()
  File "/opt/online/cores/online_o8r436/addons-own/utm/models/ir_http.py", line 37, in _dispatch
    response = super(IrHttp, self)._dispatch()
  File "/opt/online/cores/online_o8r436/odoo/openerp/addons/base/ir/ir_http.py", line 175, in _dispatch
    return self._handle_exception(e)
  File "/opt/online/cores/online_o8r436/odoo/addons/website/models/ir_http.py", line 196, in _handle_exception
    return super(ir_http, self)._handle_exception(exception)
  File "/opt/online/cores/online_o8r436/addons-own/utm/models/ir_http.py", line 42, in _handle_exception
    response = super(IrHttp, self)._handle_exception(exc)
  File "/opt/online/cores/online_o8r436/odoo/openerp/addons/base/ir/ir_http.py", line 145, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/online/cores/online_o8r436/odoo/openerp/http.py", line 675, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/online/cores/online_o8r436/odoo/openerp/addons/base/ir/ir_http.py", line 171, in _dispatch
    result = request.dispatch()
  File "/opt/online/cores/online_o8r436/odoo/openerp/http.py", line 693, in dispatch
    r = self._call_function(**self.params)
  File "/opt/online/cores/online_o8r436/odoo/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/online/cores/online_o8r436/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/online/cores/online_o8r436/odoo/openerp/http.py", line 316, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/online/cores/online_o8r436/odoo/openerp/http.py", line 812, in __call__
    return self.method(*args, **kw)
  File "/opt/online/cores/online_o8r436/odoo/openerp/http.py", line 412, in response_wrap
    response = f(*args, **kw)
  File "/opt/online/cores/online_o8r436/addons-thirdparty/oca/connector/connector/controllers/main.py", line 96, in runjob
    self._try_perform_job(session_hdl, job)
  File "/opt/online/cores/online_o8r436/addons-thirdparty/oca/connector/connector/controllers/main.py", line 66, in _try_perform_job
    job.perform(session)
  File "/opt/online/cores/online_o8r436/addons-thirdparty/oca/connector/connector/queue/job.py", line 512, in perform
    self.result = self.func(session, *self.args, **self.kwargs)
  File "/opt/online/cores/online_o8r436/addons-own/fso_website_email_screenshot_async/job.py", line 37, in render_screenshot
    template.screenshot_update()
  File "/opt/online/cores/online_o8r436/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/online/cores/online_o8r436/addons-own/fso_website_email/models/email_template.py", line 368, in screenshot_update
    raise e
AssertionError: Could not create screenshot_img!
2021-07-28 09:04:21,461 20307 INFO cona werkzeug: 192.168.37.113 - - [28/Jul/2021 09:04:21] "GET /website/image/ir.attachment/126_51fe041/datas HTTP/1.1" 200 -

**Comment by winston6071** [comment]
DNS checks ob er kurzfristig nicht hinkommt
