### ISSUE TITLE
Wenn beim popup tool kein anfangs oder enddatum gesetzt ist error beim payment button to provider

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#38]
Bird tests .... 
Ich bekam plötzlich einen fehler beim Payment nachdem ich beim Spendenprodukt das jährliche interval in kombination mit onepage checkout eingerichtet hatte.  

nach ausfüllen datum beim popup kein fehler mehr 

JOE ERNEUTER CHECK FÜR WIEDERREPRODUKTION 

CHECK 2:
 Fehler wenn OnePageCheckout Konfiguriert ist mit der Zahlschein methode 
Traceback (most recent call last):
  File "/opt/online/online_o8r34/odoo/addons/website/models/ir_http.py", line 199, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_http.py", line 145, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/online/online_o8r34/odoo/openerp/http.py", line 668, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_http.py", line 171, in _dispatch
    result = request.dispatch()
  File "/opt/online/online_o8r34/odoo/openerp/http.py", line 686, in dispatch
    r = self._call_function(*_self.params)
  File "/opt/online/online_o8r34/odoo/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/online/online_o8r34/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/online/online_o8r34/odoo/openerp/http.py", line 309, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/online/online_o8r34/odoo/openerp/http.py", line 805, in __call__
    return self.method(_args, *_kw)
  File "/opt/online/online_o8r34/odoo/openerp/http.py", line 405, in response_wrap
    response = f(_args, *_kw)
  File "/opt/online/online_o8r34/addons-loaded/website_sale_donate/controllers/main.py", line 66, in product
    self.cart_update(*_kwargs)
  File "/opt/online/online_o8r34/odoo/openerp/http.py", line 405, in response_wrap
    response = f(_args, **kw)
  File "/opt/online/online_o8r34/addons-loaded/website_sale_donate/controllers/main.py", line 256, in cart_update
    request.redirect('/shop/product/' + product.product_tmpl_id.id + '?' + request.httprequest.query_string)
TypeError: cannot concatenate 'str' and 'int' objects

Fehler bezüglich Popup: --> check nochmal reproduzierbarbeit 
2016-09-20 09:42:21,866 24862 INFO bird openerp.addons.payment_transfer.controllers.main: Beginning form_feedback with post data {'amount': u'35.0',
 'currency': u'EUR',
 'reference': u'SO052',
 'return_url': u'/shop/payment/validate'}
2016-09-20 09:42:21,870 24862 INFO bird openerp.addons.payment_transfer.models.payment_acquirer: Validated transfer payment for tx SO052: set as pending
2016-09-20 09:42:22,058 24862 INFO bird werkzeug: 192.168.37.113 - - [20/Sep/2016 09:42:22] "POST /payment/transfer/feedback HTTP/1.0" 500 -
2016-09-20 09:42:22,087 24862 ERROR bird werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/online/online_o8r34/odoo/openerp/service/server.py", line 290, in app
    return self.app(e, s)
  File "/opt/online/online_o8r34/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/opt/online/online_o8r34/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/online/online_o8r34/odoo/openerp/http.py", line 1292, in **call**
    return self.dispatch(environ, start_response)
  File "/opt/online/online_o8r34/odoo/openerp/http.py", line 1266, in **call**
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in **call**
    return self.app(environ, start_response)
  File "/opt/online/online_o8r34/odoo/openerp/http.py", line 1439, in dispatch
    result = ir_http._dispatch()
  File "/opt/online/online_o8r34/addons-own/website_as_widget/controllers/main.py", line 27, in _dispatch
    response = super(ir_http, self)._dispatch()
  File "/opt/online/online_o8r34/odoo/addons/crm/ir_http.py", line 13, in _dispatch
    response = super(ir_http, self)._dispatch()
  File "/opt/online/online_o8r34/odoo/addons/website/models/ir_http.py", line 148, in _dispatch
    resp = super(ir_http, self)._dispatch()
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_http.py", line 175, in _dispatch
    return self._handle_exception(e)
  File "/opt/online/online_o8r34/odoo/addons/website/models/ir_http.py", line 196, in _handle_exception
    return super(ir_http, self)._handle_exception(exception)
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_http.py", line 145, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/online/online_o8r34/odoo/openerp/http.py", line 668, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_http.py", line 171, in _dispatch
    result = request.dispatch()
  File "/opt/online/online_o8r34/odoo/openerp/http.py", line 686, in dispatch
    r = self._call_function(*_self.params)
  File "/opt/online/online_o8r34/odoo/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/online/online_o8r34/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/online/online_o8r34/odoo/openerp/http.py", line 309, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/online/online_o8r34/odoo/openerp/http.py", line 805, in __call__
    return self.method(_args, *_kw)
  File "/opt/online/online_o8r34/odoo/openerp/http.py", line 405, in response_wrap
    response = f(_args, *_kw)
  File "/opt/online/online_o8r34/odoo/addons/payment_transfer/controllers/main.py", line 21, in transfer_form_feedback
    request.registry['payment.transaction'].form_feedback(cr, uid, post, 'transfer', context)
  File "/opt/online/online_o8r34/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/online/online_o8r34/addons-own/website_sale_donate/models/website_sale_donate.py", line 574, in form_feedback
    res = super(PaymentTransaction, self).form_feedback(cr, uid, data, acquirer_name, context=context)
  File "/opt/online/online_o8r34/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/online/online_o8r34/odoo/addons/website_sale/models/payment.py", line 28, in form_feedback
    self.pool['sale.order'].force_quotation_send(cr, SUPERUSER_ID, [tx.sale_order_id.id], context=context)
  File "/opt/online/online_o8r34/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/online/online_o8r34/odoo/addons/sale/sale.py", line 674, in force_quotation_send
    composer_values.update(composer_obj.onchange_template_id(cr, uid, None, _template_values, context=context).get('value', {}))
  File "/opt/online/online_o8r34/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, *_kwargs)
  File "/opt/online/online_o8r34/odoo/addons/email_template/wizard/mail_compose_message.py", line 104, in onchange_template_id
    values = self.generate_email_for_composer_batch(cr, uid, template_id, [res_id], context=context)[res_id]
  File "/opt/online/online_o8r34/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/online/online_o8r34/odoo/addons/email_template/wizard/mail_compose_message.py", line 168, in generate_email_for_composer_batch
    template_values = self.pool.get('email.template').generate_email_batch(cr, uid, template_id, res_ids, fields=fields, context=ctx)
  File "/opt/online/online_o8r34/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/online/online_o8r34/odoo/addons/email_template/email_template.py", line 526, in generate_email_batch
    result, format = self.pool['report'].get_pdf(cr, uid, [res_id], report_service, context=ctx), 'pdf'
  File "/opt/online/online_o8r34/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/online/online_o8r34/odoo/addons/report/models/report.py", line 191, in get_pdf
    html = self.get_html(cr, uid, ids, report_name, data=data, context=context)
  File "/opt/online/online_o8r34/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/online/online_o8r34/odoo/addons/report/models/report.py", line 176, in get_html
    return self.render(cr, uid, [], report.report_name, docargs, context=context)
  File "/opt/online/online_o8r34/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/online/online_o8r34/odoo/addons/website_report/report.py", line 47, in render
    return super(Report, self).render(cr, uid, ids, template, values=values, context=context)
  File "/opt/online/online_o8r34/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/online/online_o8r34/odoo/addons/report/models/report.py", line 152, in render
    return view_obj.render(cr, uid, template, values, context=context)
  File "/opt/online/online_o8r34/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/online/online_o8r34/odoo/addons/website/models/ir_ui_view.py", line 173, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/opt/online/online_o8r34/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_ui_view.py", line 1022, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/opt/online/online_o8r34/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_qweb.py", line 263, in render
    return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_qweb.py", line 302, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_qweb.py", line 323, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_qweb.py", line 300, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_qweb.py", line 447, in render_tag_call
    return self.render(cr, uid, template, d)
  File "/opt/online/online_o8r34/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_qweb.py", line 263, in render
    return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_qweb.py", line 302, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_qweb.py", line 323, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_qweb.py", line 300, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_qweb.py", line 447, in render_tag_call
    return self.render(cr, uid, template, d)
  File "/opt/online/online_o8r34/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_qweb.py", line 263, in render
    return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_qweb.py", line 302, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_qweb.py", line 323, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_qweb.py", line 302, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_qweb.py", line 323, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_qweb.py", line 302, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_qweb.py", line 323, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_qweb.py", line 302, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_qweb.py", line 323, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_qweb.py", line 300, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_qweb.py", line 432, in render_tag_if
    if self.eval_bool(template_attributes["if"], qwebcontext):
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_qweb.py", line 238, in eval_bool
    return int(bool(self.eval(expr, qwebcontext)))
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_qweb.py", line 207, in eval
    raise_qweb_exception(message="Could not evaluate expression %r" % expr, expression=expr, template=template)
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_qweb.py", line 204, in eval
    return qwebcontext.safe_eval(expr)
  File "/opt/online/online_o8r34/odoo/openerp/addons/base/ir/ir_qweb.py", line 89, in safe_eval
    return eval(expr, None, locals_dict, nocopy=True, locals_builtins=True)
  File "/opt/online/online_o8r34/odoo/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>

QWebException: "'NoneType' object has no attribute 'website_popup_start'" while evaluating
"request             and not request.session.get('website_popup_cancel')             and not request.params.get('no_popup_box')             and ( False if not website.website_popup_start else datetime.datetime.strptime(website.website_popup_start, '%Y-%m-%d %H:%M:%S') <= datetime.datetime.utcnow() )             and ( True if not website.website_popup_end else datetime.datetime.utcnow() < datetime.datetime.strptime(website.website_popup_end, '%Y-%m-%d %H:%M:%S') )"

**Comment by michaelkarrer81** [comment]
@winston6071 please check :)

**Comment by winston6071** [comment]
Auch dieser Fehler is in der Demo Datenbank nicht reproduzierbar
