### ISSUE TITLE
Fehlermeldung bei klick auf "meine Zeiterfassung" Formularansicht 

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#46]
**Test1:** 
- eingeloggt als user 
- "Personal" "Zeiterfassung" "Meine Zeiterfassung" --> standard View ist Form Ansicht --> FEHLER

- selbes Menü in der Tree Ansicht --> OK 
- bei klick unter zu bestätigende Zeiterfassungen (Treeview geht) single Formview --> FEHLER 

- Login anderer User Sabine Harrer -- FEHLER
- Login as admin --> FEHLER 

**FEHLER -- Fehlermeldungsdetail:** 
2016-12-02 12:54:20,439 2731 INFO dadi werkzeug: 192.168.37.113 - - [02/Dec/2016 12:54:20] "POST /web/dataset/call_kw/hr_timesheet_sheet.sheet/fields_view_get HTTP/1.0" 200 -
2016-12-02 12:54:20,498 2731 INFO dadi werkzeug: 192.168.37.113 - - [02/Dec/2016 12:54:20] "POST /web/dataset/call_kw/ir.filters/get_filters HTTP/1.0" 200 -
2016-12-02 12:54:20,505 2731 INFO dadi werkzeug: 192.168.37.113 - - [02/Dec/2016 12:54:20] "POST /web/dataset/call_kw/hr_timesheet_sheet.sheet/fields_get HTTP/1.0" 200 -
2016-12-02 12:54:20,516 2731 INFO dadi werkzeug: 192.168.37.113 - - [02/Dec/2016 12:54:20] "POST /web/dataset/call_kw/hr_timesheet_sheet.sheet/fields_view_get HTTP/1.0" 200 -
2016-12-02 12:54:20,734 2731 ERROR dadi openerp.sql_db: bad query: SELECT "hr_timesheet_sheet_sheet_day_cat_detail".id FROM "hr_timesheet_sheet_sheet_day_cat_detail" WHERE ("hr_timesheet_sheet_sheet_day_cat_detail"."timesheet_id" in (100192)) ORDER BY "hr_timesheet_sheet_sheet_day_cat_detail"."name"  
Traceback (most recent call last):
  File "/opt/online/online_o8r36/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
DataError: integer out of range

2016-12-02 12:54:20,734 2731 ERROR dadi openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/online/online_o8r36/odoo/openerp/http.py", line 539, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/online/online_o8r36/odoo/openerp/http.py", line 576, in dispatch
    result = self._call_function(**self.params)
  File "/opt/online/online_o8r36/odoo/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/online/online_o8r36/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/online/online_o8r36/odoo/openerp/http.py", line 309, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/online/online_o8r36/odoo/openerp/http.py", line 805, in __call__
    return self.method(*args, **kw)
  File "/opt/online/online_o8r36/odoo/openerp/http.py", line 405, in response_wrap
    response = f(*args, **kw)
  File "/opt/online/online_o8r36/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/online/online_o8r36/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/online/online_o8r36/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/online/online_o8r36/odoo/openerp/models.py", line 3144, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/online/online_o8r36/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/online/online_o8r36/odoo/openerp/models.py", line 3179, in read
    self._read_from_database(stored, inherited)
  File "/opt/online/online_o8r36/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/online/online_o8r36/odoo/openerp/models.py", line 3366, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/opt/online/online_o8r36/odoo/openerp/osv/fields.py", line 775, in get
    records = comodel.search(domain, limit=self._limit)
  File "/opt/online/online_o8r36/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/online/online_o8r36/odoo/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/online/online_o8r36/odoo/openerp/models.py", line 1646, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/opt/online/online_o8r36/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/online/online_o8r36/odoo/openerp/models.py", line 4691, in _search
    cr.execute(query_str, where_clause_params)
  File "/opt/online/online_o8r36/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/online/online_o8r36/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
DataError: integer out of range

2016-12-02 12:54:20,736 2731 INFO dadi werkzeug: 192.168.37.113 - - [02/Dec/2016 12:54:20] "POST /web/dataset/call_kw/hr_timesheet_sheet.sheet/read HTTP/1.0" 200 -

**weiterführende TESTS:** 
-- download proj db und testen von installation camadeus hr modul und hr_overtime  ....... nach Anlegen eines Vertrages und die Zuweisung beim Admin sowie das Speichern eines Zeitzettels ist KEIN FEHLER ersichtlich. 
-- Anlegen eines normalen Users mit minimal rechten 
    Login Logout --> OK 
    Timesheet speichern --> OK 
    Formview aufmachen meine Zeiten und alle anderen Menüs --> OK 

DEINSTALLATION --> Modul Calender_log --> klick Zeiterfassung --> KEIN FEHLER MEHR

**Comment by michaelkarrer81** [comment]
needed to cast the view to bigint for the ids
