### ISSUE TITLE
Broken Contact Form Snippet on Installation 

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#62]
Install "contact form Snippet" 
Website Legal Page enabled --> TEST with DISABLED TOO Same Problem 

2017-03-14 10:47:51,413 2111 ERROR bird openerp.addons.base.ir.ir_ui_view: Element '<xpath expr="//form/div/div/button/../..">' kann nicht in der übergeordneten Ansicht lokalisiert werden.

Fehler Kontext:
Ansicht `Add privacy policy checkbox`
[view_id: 1942, xml_id: k. A., model: k. A., parent_id: 1290]
2017-03-14 10:47:51,418 2111 ERROR bird openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/online/online_o8r52/odoo/openerp/http.py", line 539, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/online/online_o8r52/odoo/openerp/http.py", line 576, in dispatch
    result = self._call_function(**self.params)
  File "/opt/online/online_o8r52/odoo/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/online/online_o8r52/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/online/online_o8r52/odoo/openerp/http.py", line 309, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/online/online_o8r52/odoo/openerp/http.py", line 805, in __call__
    return self.method(*args, **kw)
  File "/opt/online/online_o8r52/odoo/openerp/http.py", line 405, in response_wrap
    response = f(*args, **kw)
  File "/opt/online/online_o8r52/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/online/online_o8r52/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/online/online_o8r52/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/online/online_o8r52/odoo/openerp/addons/base/res/res_config.py", line 586, in execute
    action = self._install_modules(cr, uid, to_install, context=context)
  File "/opt/online/online_o8r52/odoo/openerp/addons/base/res/res_config.py", line 55, in _install_modules
    result = ir_module.button_immediate_install(cr, uid, to_install_ids, context=context)
  File "/opt/online/online_o8r52/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/online/online_o8r52/odoo/openerp/addons/base/module/module.py", line 447, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/online/online_o8r52/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/online/online_o8r52/odoo/openerp/addons/base/module/module.py", line 495, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/online/online_o8r52/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/online/online_o8r52/odoo/openerp/modules/loading.py", line 354, in load_modules
    loaded_modules, update_module)
  File "/opt/online/online_o8r52/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/online/online_o8r52/odoo/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/online/online_o8r52/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/online/online_o8r52/odoo/openerp/tools/convert.py", line 900, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/online/online_o8r52/odoo/openerp/tools/convert.py", line 986, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/online/online_o8r52/odoo/openerp/tools/convert.py", line 852, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/online/online_o8r52/odoo/openerp/tools/convert.py", line 826, in _tag_template
    return self._tag_record(cr, record, data_node)
  File "/opt/online/online_o8r52/odoo/openerp/tools/convert.py", line 762, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/online/online_o8r52/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/online/online_o8r52/odoo/openerp/addons/base/ir/ir_model.py", line 1065, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/online/online_o8r52/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/online/online_o8r52/odoo/openerp/addons/base/ir/ir_ui_view.py", line 255, in create
    context=context)
  File "/opt/online/online_o8r52/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/online/online_o8r52/odoo/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/online/online_o8r52/odoo/openerp/models.py", line 4093, in create
    record = self.browse(self._create(old_vals))
  File "/opt/online/online_o8r52/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/online/online_o8r52/odoo/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/online/online_o8r52/odoo/openerp/models.py", line 4284, in _create
    recs._validate_fields(vals)
  File "/opt/online/online_o8r52/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/online/online_o8r52/odoo/openerp/models.py", line 1271, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Feld(er) 'arch' verletzen eine Einschr\xe4nkung: Invalid view definition

Fehlerdetails:
Element '<xpath expr="//form/div/div/button/../..">' kann nicht in der \xfcbergeordneten Ansicht lokalisiert werden.

Fehler Kontext:
Ansicht `Add privacy policy checkbox`
[view_id: 1942, xml_id: k. A., model: k. A., parent_id: 1290]" while parsing None:8, near
<data inherit_id="website_crm.contactus_form" name="Add privacy policy checkbox">
    <xpath expr="//form/div/div/button/../.." position="before">
        <div t-attf-class="form-group #{error and 'terms' in error and 'has-error' or ''}">
            <label class="col-md-3 col-sm-4 control-label" for="terms"/>
            <div class="col-md-7 col-sm-8">
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="privacy_policy" required="True"/>
                        I have read and accept the
                        <a href="/page/privacy" target="_blank" title="Privacy Policy">Privacy Policy</a>.
                    </label>
                </div>
            </div>
        </div>
    </xpath>
</data>
2017-03-14 10:47:51,425 2111 INFO bird openerp.modules.loading: loading 1 modules...

**Comment by michaelkarrer81** [comment]
Done
