### ISSUE TITLE
[fsonline_widget_manager] Aswidget Button Check error message und error im log 

### ISSUE THREAD

**Issue by winston6071** [OpenAT/online#75]
Diese Meldung beim widget check ist wahrscheinlich normal da ich ja beim einbinden jetzt das NICHT in den HEAD kopiert habe sondern alles im body hab. Vielleicht könnte man die noch abfangen und als Rote message wie die anderen anzeigen das der Kunde net panik bekommt

2017-04-14 10:51:13,660 11283 ERROR gl2k openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/online/online_o8r54/odoo/openerp/http.py", line 539, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/online/online_o8r54/odoo/openerp/http.py", line 576, in dispatch
    result = self._call_function(**self.params)
  File "/opt/online/online_o8r54/odoo/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/online/online_o8r54/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/online/online_o8r54/odoo/openerp/http.py", line 309, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/online/online_o8r54/odoo/openerp/http.py", line 805, in __call__
    return self.method(*args, **kw)
  File "/opt/online/online_o8r54/odoo/openerp/http.py", line 405, in response_wrap
    response = f(*args, **kw)
  File "/opt/online/online_o8r54/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/online/online_o8r54/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/online/online_o8r54/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/online/online_o8r54/odoo/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/online/online_o8r54/addons-loaded/website_widget_manager/models/models.py", line 224, in action_check_widget
    elif 'head' not in target_tree.getpath(script_iframeresizer[0]):
AttributeError: 'HtmlElement' object has no attribute 'getpath'
2017-04-14 10:51:13,662 11283 INFO gl2k werkzeug: 192.168.37.113 - - [14/Apr/2017 10:51:13] "POST /web/dataset/call_button HTTP/1.0" 200 -

**Comment by michaelkarrer81** [comment]
Done
